language: go

go:
  - 1.10.x

before_install:
  - go get -v github.com/golang/lint/golint
  - go get -v gopkg.in/yaml.v2  
  - go get -v gopkg.in/src-d/go-git.v4/...
  - go get -v github.com/kataras/iris
